### PR TITLE
Multiple file selection & commit window's context menu

### PR DESCRIPTION
**Pull request by dgomolka**
- Multiple file selection
- Plugin now included in local changes context menu

### CODE REVIEW

**Comment by Drjacky** [comment]
> & commit window's context menu

Could you please attach a screenshot? I do not see it in the right-click in the "Commit Changes" dialog.

**Comment by Drjacky** [comment]
Nor in the "Local Changes"
Screenshot 2024-01-30 at 09 42 55

**Comment by Drjacky** [comment]
> > & commit window's context menu
> 
> Could you please attach a screenshot? I do not see it in the right-click in the "Commit Changes" dialog.

Nevermind! It is in the "Local Changes"

**Comment by Drjacky** [comment]
Please set `<add-to-group group-id="ChangesViewPopupMenu" anchor="last" />` to `first` in the `plugin.xml`

**Comment by dgomolka** [comment]
I think that keeping VCS as the first group in the commit window is important as "muscle memory" or however to call it would be at play here for many people but if you want to keep it first, no problem, I can change it

**Comment by Drjacky** [comment]
> I think that keeping VCS as the first group in the commit window is important as "muscle memory" or however to call it would be at play here for many people but if you want to keep it first, no problem, I can change it

Hmmm, that could be true. My reason was in the editor context it's on top and I just wanted to have the same order in other places too. But you're right, VCS section is much important!

**Review by Drjacky — APPROVED** [review]
Great work! 🚀

**Pull request merged**
